### ISSUE TITLE
Problem retrieving studies 

### ISSUE THREAD

**Issue by gsantia** [kids-first/kf-api-study-creator#751] opened 2021-09-22 14:20 UTC
In both local and deployed dev environments of the data tracker manual testing can't be done because when trying to access "My Studies", the following error comes up:

<img width="1335" alt="Screen Shot 2021-09-22 at 10 16 23 AM" src="https://user-images.githubusercontent.com/24629414/134360735-5c4e3a60-b0bb-431d-95dc-a8152211851f.png">

Running data tracker instances off the [flatfile-mutation branch](https://github.com/kids-first/kf-api-study-creator/tree/flatfile-mutation) solves this issue, so #744 should close this.

**Comment by znatty22** [comment] 2021-09-28 15:56
Closing because I don't think this is a real bug. It is probably due to the frontend and backend being inconsistent states perhaps caused by the file type migration. Additionally, I can't reproduce this issue

**Closed by znatty22** 2021-09-28 15:56 UTC
Labels: bug
